# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.14

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.14.3/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.14.3/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/Owen/Desktop/rojo/cis330_project_group_3

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/Owen/Desktop/rojo/cis330_project_group_3

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.14.3/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.14.3/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/Owen/Desktop/rojo/cis330_project_group_3/CMakeFiles /Users/Owen/Desktop/rojo/cis330_project_group_3/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/Owen/Desktop/rojo/cis330_project_group_3/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Checkers

# Build rule for target.
Checkers: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Checkers
.PHONY : Checkers

# fast build rule for target.
Checkers/fast:
	$(MAKE) -f CMakeFiles/Checkers.dir/build.make CMakeFiles/Checkers.dir/build
.PHONY : Checkers/fast

Board.o: Board.cc.o

.PHONY : Board.o

# target to build an object file
Board.cc.o:
	$(MAKE) -f CMakeFiles/Checkers.dir/build.make CMakeFiles/Checkers.dir/Board.cc.o
.PHONY : Board.cc.o

Board.i: Board.cc.i

.PHONY : Board.i

# target to preprocess a source file
Board.cc.i:
	$(MAKE) -f CMakeFiles/Checkers.dir/build.make CMakeFiles/Checkers.dir/Board.cc.i
.PHONY : Board.cc.i

Board.s: Board.cc.s

.PHONY : Board.s

# target to generate assembly for a file
Board.cc.s:
	$(MAKE) -f CMakeFiles/Checkers.dir/build.make CMakeFiles/Checkers.dir/Board.cc.s
.PHONY : Board.cc.s

CLI.o: CLI.cc.o

.PHONY : CLI.o

# target to build an object file
CLI.cc.o:
	$(MAKE) -f CMakeFiles/Checkers.dir/build.make CMakeFiles/Checkers.dir/CLI.cc.o
.PHONY : CLI.cc.o

CLI.i: CLI.cc.i

.PHONY : CLI.i

# target to preprocess a source file
CLI.cc.i:
	$(MAKE) -f CMakeFiles/Checkers.dir/build.make CMakeFiles/Checkers.dir/CLI.cc.i
.PHONY : CLI.cc.i

CLI.s: CLI.cc.s

.PHONY : CLI.s

# target to generate assembly for a file
CLI.cc.s:
	$(MAKE) -f CMakeFiles/Checkers.dir/build.make CMakeFiles/Checkers.dir/CLI.cc.s
.PHONY : CLI.cc.s

Score.o: Score.cc.o

.PHONY : Score.o

# target to build an object file
Score.cc.o:
	$(MAKE) -f CMakeFiles/Checkers.dir/build.make CMakeFiles/Checkers.dir/Score.cc.o
.PHONY : Score.cc.o

Score.i: Score.cc.i

.PHONY : Score.i

# target to preprocess a source file
Score.cc.i:
	$(MAKE) -f CMakeFiles/Checkers.dir/build.make CMakeFiles/Checkers.dir/Score.cc.i
.PHONY : Score.cc.i

Score.s: Score.cc.s

.PHONY : Score.s

# target to generate assembly for a file
Score.cc.s:
	$(MAKE) -f CMakeFiles/Checkers.dir/build.make CMakeFiles/Checkers.dir/Score.cc.s
.PHONY : Score.cc.s

Tile.o: Tile.cc.o

.PHONY : Tile.o

# target to build an object file
Tile.cc.o:
	$(MAKE) -f CMakeFiles/Checkers.dir/build.make CMakeFiles/Checkers.dir/Tile.cc.o
.PHONY : Tile.cc.o

Tile.i: Tile.cc.i

.PHONY : Tile.i

# target to preprocess a source file
Tile.cc.i:
	$(MAKE) -f CMakeFiles/Checkers.dir/build.make CMakeFiles/Checkers.dir/Tile.cc.i
.PHONY : Tile.cc.i

Tile.s: Tile.cc.s

.PHONY : Tile.s

# target to generate assembly for a file
Tile.cc.s:
	$(MAKE) -f CMakeFiles/Checkers.dir/build.make CMakeFiles/Checkers.dir/Tile.cc.s
.PHONY : Tile.cc.s

Tree.o: Tree.cpp.o

.PHONY : Tree.o

# target to build an object file
Tree.cpp.o:
	$(MAKE) -f CMakeFiles/Checkers.dir/build.make CMakeFiles/Checkers.dir/Tree.cpp.o
.PHONY : Tree.cpp.o

Tree.i: Tree.cpp.i

.PHONY : Tree.i

# target to preprocess a source file
Tree.cpp.i:
	$(MAKE) -f CMakeFiles/Checkers.dir/build.make CMakeFiles/Checkers.dir/Tree.cpp.i
.PHONY : Tree.cpp.i

Tree.s: Tree.cpp.s

.PHONY : Tree.s

# target to generate assembly for a file
Tree.cpp.s:
	$(MAKE) -f CMakeFiles/Checkers.dir/build.make CMakeFiles/Checkers.dir/Tree.cpp.s
.PHONY : Tree.cpp.s

main.o: main.cc.o

.PHONY : main.o

# target to build an object file
main.cc.o:
	$(MAKE) -f CMakeFiles/Checkers.dir/build.make CMakeFiles/Checkers.dir/main.cc.o
.PHONY : main.cc.o

main.i: main.cc.i

.PHONY : main.i

# target to preprocess a source file
main.cc.i:
	$(MAKE) -f CMakeFiles/Checkers.dir/build.make CMakeFiles/Checkers.dir/main.cc.i
.PHONY : main.cc.i

main.s: main.cc.s

.PHONY : main.s

# target to generate assembly for a file
main.cc.s:
	$(MAKE) -f CMakeFiles/Checkers.dir/build.make CMakeFiles/Checkers.dir/main.cc.s
.PHONY : main.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... Checkers"
	@echo "... Board.o"
	@echo "... Board.i"
	@echo "... Board.s"
	@echo "... CLI.o"
	@echo "... CLI.i"
	@echo "... CLI.s"
	@echo "... Score.o"
	@echo "... Score.i"
	@echo "... Score.s"
	@echo "... Tile.o"
	@echo "... Tile.i"
	@echo "... Tile.s"
	@echo "... Tree.o"
	@echo "... Tree.i"
	@echo "... Tree.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

